"""postmarkdown

Revision ID: 2263f58e81a
Revises: 467fd10d634
Create Date: 2016-07-07 22:51:10.301644

"""

# revision identifiers, used by Alembic.
revision = '2263f58e81a'
down_revision = '467fd10d634'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
