"""avatar

Revision ID: 3e519a41629
Revises: 174604d73f8
Create Date: 2016-07-06 16:04:34.412009

"""

# revision identifiers, used by Alembic.
revision = '3e519a41629'
down_revision = '174604d73f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
