"""init migrations

Revision ID: 42b069dad6a
Revises: 367002417bb
Create Date: 2016-07-12 13:24:24.688983

"""

# revision identifiers, used by Alembic.
revision = '42b069dad6a'
down_revision = '367002417bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
