"""nopoststimestamp

Revision ID: 467fd10d634
Revises: 57ac8d56cd5
Create Date: 2016-07-07 18:10:58.907859

"""

# revision identifiers, used by Alembic.
revision = '467fd10d634'
down_revision = '57ac8d56cd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
