"""tryblogpost

Revision ID: 57ac8d56cd5
Revises: 18f75e99f7c
Create Date: 2016-07-07 15:16:01.490371

"""

# revision identifiers, used by Alembic.
revision = '57ac8d56cd5'
down_revision = '18f75e99f7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
